vim.cmd("set expandtab")
vim.cmd("set scrolloff=12")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set noswapfile")
vim.cmd("set relativenumber")
vim.cmd("set mouse=a")
vim.g.mapleader = " "
vim.cmd("nnoremap <leader>v :vsplit<CR>")
vim.cmd("nnoremap <leader>h :split<CR>")
